CREATE TABLE public.names (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    active boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX names_name_key ON public.names USING btree (name);