CREATE TABLE public.words (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficulty integer NOT NULL,
    value varchar NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    active boolean NOT NULL DEFAULT true,
    similarity_threshold float4 NOT NULL DEFAULT 1.0
);

CREATE UNIQUE INDEX words_value_key ON public.words USING btree (value);
