-- Source for the words used in the game

CREATE TABLE public.words (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficulty integer NOT NULL,
    value varchar NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    active boolean NOT NULL DEFAULT true,
    similarity_threshold float4 NOT NULL DEFAULT 1.0
);

ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX words_value_key ON public.words USING btree (value);
