CREATE TABLE public.game (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar UNIQUE DEFAULT generate_game_name(),
    password varchar NULL,
    code varchar UNIQUE DEFAULT generate_game_code(),
    created_at timestamp NOT NULL DEFAULT now(),
    created_by varchar NOT NULL,
    rounds integer NOT NULL,
    difficulty integer NOT NULL
);

CREATE UNIQUE INDEX game_code_key ON public.game USING btree (code);
CREATE UNIQUE INDEX game_name_key ON public.game USING btree (name);
