CREATE TABLE public.player (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id integer NOT NULL REFERENCES public.game(id),
    name varchar NOT NULL,
    avatar varchar NOT NULL,
    score numeric NOT NULL DEFAULT 0,
    code varchar NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX unique_game_player ON public.player USING btree (game_id, name);
