CREATE TABLE public.game_rounds (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id integer NOT NULL REFERENCES public.game(id),
    painter_id integer NOT NULL REFERENCES public.player(id),
    round integer NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    game_word_id integer NOT NULL REFERENCES public.game_words(id)
);

CREATE UNIQUE INDEX unique_game_rounds_painter ON public.game_rounds USING btree (game_id, painter_id, round);
CREATE UNIQUE INDEX unique_game_rounds_word ON public.game_rounds USING btree (game_id, game_word_id);
