-- Stores relevant details for each turn in a game

CREATE TABLE public.game_rounds (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id integer NOT NULL REFERENCES public.game(id),
    painter_id integer NOT NULL REFERENCES public.player(id),
    round integer NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    game_word_id integer NOT NULL REFERENCES public.game_words(id)
);

ALTER TABLE public.game_rounds ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX unique_game_rounds_painter ON public.game_rounds USING btree (game_id, painter_id, round);
CREATE UNIQUE INDEX unique_game_rounds_word ON public.game_rounds USING btree (game_id, game_word_id);
CREATE INDEX idx_game_rounds_game_word_id ON public.game_rounds USING btree (game_word_id);
CREATE INDEX idx_game_rounds_painter_id ON public.game_rounds USING btree (painter_id);
