DELETE FROM public.words;

INSERT INTO public.words (difficulty, value, similarity_threshold)
VALUES
-- easy
  (1, 'Rocket', DEFAULT),
  (1, 'Robot', DEFAULT),
  (1, 'Snowman', DEFAULT),
  (1, 'Pirate ship', DEFAULT),
  (1, 'Ferris wheel', DEFAULT),
  (1, 'Hot air balloon', DEFAULT),
  (1, 'Treasure chest', DEFAULT),
  (1, 'Lighthouse', DEFAULT),
  (1, 'Castle', DEFAULT),
  (1, 'Tent', DEFAULT),
  (1, 'Umbrella', DEFAULT),
  (1, 'Kite', DEFAULT),
  (1, 'Balloon', DEFAULT),
  (1, 'Skateboard', DEFAULT),
  (1, 'Slide', DEFAULT),
  (1, 'Swing', DEFAULT),
  (1, 'Seesaw', DEFAULT),
  (1, 'Ladder', DEFAULT),
  (1, 'Bridge', DEFAULT),
  (1, 'Tower', DEFAULT),

  (1, 'Surfing', DEFAULT),
  (1, 'Juggling', DEFAULT),
  (1, 'Ballerina', DEFAULT),
  (1, 'Painter', DEFAULT),
  (1, 'Baker', DEFAULT),
  (1, 'Bus driver', DEFAULT),
  (1, 'Mountain climber', DEFAULT),
  (1, 'Shopping', DEFAULT),
  (1, 'Fisherman', DEFAULT),
  (1, 'Skydiver', DEFAULT),
  (1, 'Rockstar', DEFAULT),
  (1, 'Referee', DEFAULT),
  (1, 'Coach', DEFAULT),
  (1, 'Unicycle', DEFAULT),
  (1, 'Jumping rope', DEFAULT),
  (1, 'Chef', DEFAULT),
  (1, 'Barista', DEFAULT),
  (1, 'Dreaming', DEFAULT),
  (1, 'Brushing teeth', DEFAULT),
  (1, 'Taking a shower', DEFAULT),

  (1, 'Volcano', DEFAULT),
  (1, 'Desert', DEFAULT),
  (1, 'Jungle', DEFAULT),
  (1, 'Waterfall', DEFAULT),
  (1, 'Island', DEFAULT),
  (1, 'Igloo', DEFAULT),
  (1, 'Cave', DEFAULT),
  (1, 'Farm', DEFAULT),
  (1, 'Garden', DEFAULT),
  (1, 'Park', DEFAULT),
  (1, 'Beach', DEFAULT),
  (1, 'Ocean', DEFAULT),
  (1, 'River', DEFAULT),
  (1, 'Lake', DEFAULT),
  (1, 'Forest', DEFAULT),
  (1, 'Meadow', DEFAULT),
  (1, 'Hill', DEFAULT),
  (1, 'Campfire', DEFAULT),
  (1, 'Rainbow', DEFAULT),
  (1, 'Storm', DEFAULT),

  (1, 'Dragon', DEFAULT),
  (1, 'Unicorn', DEFAULT),
  (1, 'Witch', DEFAULT),
  (1, 'Wizard', DEFAULT),
  (1, 'Fairy', DEFAULT),
  (1, 'Mermaid', DEFAULT),
  (1, 'Superhero', DEFAULT),
  (1, 'Alien', DEFAULT),
  (1, 'Ghost', DEFAULT),
  (1, 'Vampire', DEFAULT),
  (1, 'Zombie', DEFAULT),
  (1, 'Knight', DEFAULT),
  (1, 'Princess', DEFAULT),
  (1, 'King', DEFAULT),
  (1, 'Queen', DEFAULT),
  (1, 'Pirate', DEFAULT),
  (1, 'Troll', DEFAULT),
  (1, 'Magic wand', DEFAULT),
  (1, 'Treasure map', DEFAULT),
  (1, 'Spaceship', DEFAULT),

  (1, 'Ice cream cone', DEFAULT),
  (1, 'Birthday cake', DEFAULT),
  (1, 'Popcorn', DEFAULT),
  (1, 'Sandwich', DEFAULT),
  (1, 'Hamburger', DEFAULT),
  (1, 'Hotdog', DEFAULT),
  (1, 'Spaghetti', DEFAULT),
  (1, 'Pancake', DEFAULT),
  (1, 'Donut', DEFAULT),
  (1, 'Cookie', DEFAULT),
  (1, 'Chocolate bar', DEFAULT),
  (1, 'Candy cane', DEFAULT),
  (1, 'Lollipop', DEFAULT),
  (1, 'French fries', DEFAULT),
  (1, 'Cupcake', DEFAULT),
  (1, 'Pumpkin', DEFAULT),
  (1, 'Watermelon', DEFAULT),
  (1, 'Pineapple', DEFAULT),
  (1, 'Corn', DEFAULT),
  (1, 'Taco', DEFAULT),

-- medium
  (2, 'Telescope', DEFAULT),
  (2, 'Microscope', DEFAULT),
  (2, 'Suitcase', DEFAULT),
  (2, 'Pogo stick', DEFAULT),
  (2, 'Roller coaster', DEFAULT),
  (2, 'Typewriter', DEFAULT),
  (2, 'Headphones', DEFAULT),
  (2, 'Camera', DEFAULT),
  (2, 'Binoculars', DEFAULT),
  (2, 'Compass', DEFAULT),
  (2, 'Umbrella hat', DEFAULT),
  (2, 'Wheelbarrow', DEFAULT),
  (2, 'Hammock', DEFAULT),
  (2, 'Tripod', DEFAULT),
  (2, 'Hourglass', DEFAULT),
  (2, 'Lantern', DEFAULT),
  (2, 'Chessboard', DEFAULT),
  (2, 'Fishing rod', DEFAULT),
  (2, 'Mailbox', DEFAULT),
  (2, 'Test tube', DEFAULT),

  (2, 'Magician', DEFAULT),
  (2, 'Playground', DEFAULT),
  (2, 'Gymnast', DEFAULT),
  (2, 'Skiing', DEFAULT),
  (2, 'Ice skating', DEFAULT),
  (2, 'Rollerblade', DEFAULT),
  (2, 'Diver', DEFAULT),
  (2, 'Pianist', DEFAULT),
  (2, 'Violinist', DEFAULT),
  (2, 'Drummer', DEFAULT),
  (2, 'DJ', DEFAULT),
  (2, 'Race car driver', DEFAULT),
  (2, 'Jockey', DEFAULT),
  (2, 'Zoo keeper', DEFAULT),
  (2, 'Pilot', DEFAULT),
  (2, 'Dragon boat', DEFAULT),
  (2, 'Sandcastle', DEFAULT),
  (2, 'Library', DEFAULT),
  (2, 'Picnic mat', DEFAULT),
  (2, 'Stick insect', DEFAULT),

  (2, 'Tornado', DEFAULT),
  (2, 'Earthquake', DEFAULT),
  (2, 'Glacier', DEFAULT),
  (2, 'Cliff', DEFAULT),
  (2, 'Canyon', DEFAULT),
  (2, 'Sewer', DEFAULT),
  (2, 'Emergency room', DEFAULT),
  (2, 'Coral reef', DEFAULT),
  (2, 'Acid rain', DEFAULT),
  (2, 'Headquarters', DEFAULT),
  (2, 'North Pole', DEFAULT),
  (2, 'Safari', DEFAULT),
  (2, 'Treehouse', DEFAULT),
  (2, 'Dam', DEFAULT),
  (2, 'Museum', DEFAULT),
  (2, 'Camping', DEFAULT),
  (2, 'Skyline', DEFAULT),
  (2, 'Skyscraper', DEFAULT),
  (2, 'Windmill', DEFAULT),
  (2, 'Ice skating rink', DEFAULT),

  (2, 'Scientist', DEFAULT),
  (2, 'Fireball', DEFAULT),
  (2, 'Big bad wolf', DEFAULT),
  (2, 'Robin hood', DEFAULT),
  (2, 'Ninja turtle', DEFAULT),
  (2, 'Giant robot', DEFAULT),
  (2, 'Lightsaber', DEFAULT),
  (2, 'Astronaut', DEFAULT),
  (2, 'Time machine', DEFAULT),
  (2, 'Sniper', DEFAULT),
  (2, 'Mummy', DEFAULT),
  (2, 'Catapult', DEFAULT),
  (2, 'Trap', DEFAULT),
  (2, 'Viking', DEFAULT),
  (2, 'Magic lamp', DEFAULT),
  (2, 'Cloning machine', DEFAULT),
  (2, 'Hologram', DEFAULT),
  (2, 'Magic carpet', DEFAULT),
  (2, 'Breakdancer', DEFAULT),
  (2, 'Haunted house', DEFAULT),

  (2, 'Chocolate fountain', DEFAULT),
  (2, 'Cotton candy', DEFAULT),
  (2, 'Milkshake', DEFAULT),
  (2, 'Lemonade', DEFAULT),
  (2, 'Sushi roll', DEFAULT),
  (2, 'Burrito', DEFAULT),
  (2, 'Ramen bowl', DEFAULT),
  (2, 'Salad bowl', DEFAULT),
  (2, 'Barbecue grill', DEFAULT),
  (2, 'Pancake syrup', DEFAULT),
  (2, 'Birthday party', DEFAULT),
  (2, 'Party hat', DEFAULT),
  (2, 'Fireworks', DEFAULT),
  (2, 'Disco ball', DEFAULT),
  (2, 'Roller skates', DEFAULT),
  (2, 'Pinata', DEFAULT),
  (2, 'Teddy bear', DEFAULT),
  (2, 'Toy robot', DEFAULT),
  (2, 'Dollhouse', DEFAULT),
  (2, 'Video game controller', DEFAULT),

-- hard
  (3, 'Freedom', DEFAULT),
  (3, 'Love', DEFAULT),
  (3, 'Friendship', DEFAULT),
  (3, 'Justice', DEFAULT),
  (3, 'Bored', DEFAULT),
  (3, 'Fear', DEFAULT),
  (3, 'Brave', DEFAULT),
  (3, 'Day dream', DEFAULT),
  (3, 'Secret', DEFAULT),
  (3, 'Memory', DEFAULT),
  (3, 'Peace', DEFAULT),
  (3, 'Anger', DEFAULT),
  (3, 'Hope', DEFAULT),
  (3, 'Luck', DEFAULT),
  (3, 'Nightmare', DEFAULT),
  (3, 'Confusion', DEFAULT),
  (3, 'Sleepwalking', DEFAULT),
  (3, 'Competition', DEFAULT),
  (3, 'Surprise', DEFAULT),
  (3, 'Teamwork', DEFAULT),

  (3, 'Valet', DEFAULT),
  (3, 'Model', DEFAULT),
  (3, 'Detective', DEFAULT),
  (3, 'Operator', DEFAULT),
  (3, 'Spy', DEFAULT),
  (3, 'Veterinarian', DEFAULT),
  (3, 'Hacker', DEFAULT),
  (3, 'Samurai', DEFAULT),
  (3, 'Fruit picker', DEFAULT),
  (3, 'Announcer', DEFAULT),
  (3, 'Tour guide', DEFAULT),
  (3, 'Blacksmith', DEFAULT),
  (3, 'Pharaoh', DEFAULT),
  (3, 'Caveman', DEFAULT),
  (3, 'Inventor', DEFAULT),
  (3, 'Judge', DEFAULT),
  (3, 'Librarian', DEFAULT),
  (3, 'Mime', DEFAULT),
  (3, 'Farmer', DEFAULT),
  (3, 'Principal', DEFAULT),

  (3, 'Time travel', DEFAULT),
  (3, 'Tug of war', DEFAULT),
  (3, 'Monk', DEFAULT),
  (3, 'Author', DEFAULT),
  (3, 'Opera', DEFAULT),
  (3, 'Meditating', DEFAULT),
  (3, 'Exercise', DEFAULT),
  (3, 'Boy scout', DEFAULT),
  (3, 'Plumber', DEFAULT),
  (3, 'Boxing', DEFAULT),
  (3, 'Wrestling', DEFAULT),
  (3, 'Golf', DEFAULT),
  (3, 'Fencing', DEFAULT),
  (3, 'Lumberjack', DEFAULT),
  (3, 'Marching band', DEFAULT),
  (3, 'Relay race', DEFAULT),
  (3, 'Paintball', DEFAULT),
  (3, 'Photographer', DEFAULT),
  (3, 'Blackboard', DEFAULT),
  (3, 'Conductor', DEFAULT),

  (3, 'Courthouse', DEFAULT),
  (3, 'Laboratory', DEFAULT),
  (3, 'Escalator', DEFAULT),
  (3, 'Observatory', DEFAULT),
  (3, 'Crater', DEFAULT),
  (3, 'Amusement park', DEFAULT),
  (3, 'Subway', DEFAULT),
  (3, 'Radar', DEFAULT),
  (3, 'Outer space', DEFAULT),
  (3, 'Foodcourt', DEFAULT),
  (3, 'Maze', DEFAULT),
  (3, 'Skatepark', DEFAULT),
  (3, 'Newsroom', DEFAULT),
  (3, 'Theater', DEFAULT),
  (3, 'Circus', DEFAULT),
  (3, 'Graveyard', DEFAULT),
  (3, 'Cheerleader', DEFAULT),
  (3, 'Parking ticket', DEFAULT),
  (3, 'Silent disco', DEFAULT),
  (3, 'Voice', DEFAULT),

  (3, 'Puppet', DEFAULT),
  (3, 'Gargoyle', DEFAULT),
  (3, 'Fountain of youth', DEFAULT),
  (3, 'Ghost ship', DEFAULT),
  (3, 'Phoenix', DEFAULT),
  (3, 'Goblin', DEFAULT),
  (3, 'Totem pole', DEFAULT),
  (3, 'Werewolf', DEFAULT),
  (3, 'Sumo wrestling', DEFAULT),
  (3, 'Figure skating', DEFAULT),
  (3, 'Excalibur', DEFAULT),
  (3, 'Mount fuji', DEFAULT),
  (3, 'Invisible man', DEFAULT),
  (3, 'Shapeshifter', DEFAULT),
  (3, 'Fortune teller', DEFAULT),
  (3, 'Niagara falls', DEFAULT),
  (3, 'Daredevil', DEFAULT),
  (3, 'Spellbook', DEFAULT),
  (3, 'Streetsweeper', DEFAULT),
  (3, 'Sculptor', DEFAULT);
